version: '3.8'
services:
  app:
    container_name: telegram-assistant
    image: "${DOCKER_IMAGE:-ghcr.io/yerkenabildin/telegram-assistant:latest}"
    restart: always
    env_file:
      - .env
    environment:
      - SCRIPT_NAME=/telegram-assistant
    volumes:
      - ${STORAGE_PATH:-./storage}:/app/storage
    ports:
      - "5050:5050"
