version: '0.0.1'
services:
  app:
    container_name: telegram-assistant
    image: "cr.yandex/crpm6kkscaeg5uqtfdqt/telegram-assistant:latest"
    restart: always
    env_file:
      - .env
    environment:
      - SCRIPT_NAME=/telegram-assistant
    volumes:
      - /home/yerken/storage/telegram-assistant:/app/storage
    ports:
      - "5050:5050"
